FROM flyway/flyway:6.5.0
COPY SQLScripts/ /flyway/sql

# Labels
LABEL maintainer="crobles@dbamastery.com"
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.name="geokidsdb-flyway"
LABEL org.label-schema.description="Database migrations custom image using Flyway"
LABEL org.label-schema.url="http://dbamastery.com"