kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-robot 
  namespace: default
subjects:
  - kind: ServiceAccount
    name: jenkins-robot 
    namespace: default
roleRef:
  kind: Role
  name: jenkins-robot 
  apiGroup: rbac.authorization.k8s.io